Update install

diff --git a/apps/Arduino/install b/apps/Arduino/install
--- a/apps/Arduino/install
+++ b/apps/Arduino/install
@@ -1,14 +1,15 @@
 #!/bin/bash
+
 version=1.8.19
 
-#determine filename of download
-if [ $arch == 32 ];then
-  filename="arduino-${version}-linuxarm.tar.xz"
-elif [ $arch == 64 ];then
-  filename="arduino-${version}-linuxaarch64.tar.xz"
-fi
+# -----------------------------
+# Determine amd64 filename
+# -----------------------------
+filename="arduino-${version}-linux64.tar.xz"
 
-#ask if user wants dark theme
+# -----------------------------
+# Ask user for dark/light theme
+# -----------------------------
 wget -qO /tmp/dark-arduino.png 'https://github.com/Botspot/DarkArduinoTheme/raw/master/dark-arduino.png'
 wget -qO /tmp/light-arduino.png 'https://github.com/Botspot/DarkArduinoTheme/raw/master/light-arduino.png'
 
@@ -21,28 +22,41 @@ yad --center --separator='\n' \
   --field='!/tmp/light-arduino.png!Light mode (default):BTN' 'bash -c "echo light; kill $YAD_PID"' | grep -qx dark &
 question_pid=$!
 
+# -----------------------------
+# Download Arduino IDE
+# -----------------------------
 cd ~/.local/share
-wget -O $PWD/$filename "https://downloads.arduino.cc/${filename}" || error "Failed to download arduino package!"
+wget -O $PWD/$filename "https://downloads.arduino.cc/${filename}" || { echo "Download failed!"; exit 1; }
 
-tar -xf $PWD/$filename || error "failed to extract with tar!"
-sudo $PWD/arduino-${version}/install.sh || error "failed run Arduino install script!"
+# Extract
+tar -xf $PWD/$filename || { echo "Extraction failed!"; exit 1; }
+
+# Install
+sudo $PWD/arduino-${version}/install.sh || { echo "Arduino install script failed!"; exit 1; }
+
+# Cleanup
 rm -f $HOME/Desktop/arduino-arduinoide.desktop $PWD/$filename
 
-if package_installed brltty ; then
-  status "Removing brltty package because it makes it impossible to connect to arduino boards..."
-  apt_lock_wait
-  sudo apt purge -y brltty | less_apt
+# Remove brltty if installed (conflicts with Arduino USB)
+if dpkg -s brltty &>/dev/null; then
+  echo "Removing brltty (can block Arduino connections)..."
+  sudo apt purge -y brltty
 fi
 
-#configure dark mode if user chose it
+# -----------------------------
+# Configure dark mode if chosen
+# -----------------------------
 wait $question_pid
-if [ $? == 0 ];then
-  status "Installing dark mode..."
-  git_clone https://github.com/Botspot/DarkArduinoTheme || exit 1
-  
+if [ $? -eq 0 ]; then
+  echo "Installing dark mode..."
+  git clone https://github.com/Botspot/DarkArduinoTheme || exit 1
   cp -r DarkArduinoTheme/theme ~/.local/share/arduino-${version}/lib
   cp -r DarkArduinoTheme/images/. ~/.local/share/arduino-${version}/lib
   rm -rf DarkArduinoTheme
-  status_green "Done"
+  echo "Dark mode installed!"
 fi
-rm -f /tmp/dark-arduino.png /tmp/dark-arduino.png
+
+# Cleanup temp images
+rm -f /tmp/dark-arduino.png /tmp/light-arduino.png
+
+echo "Arduino IDE ${version} amd64 installation complete!"
